### PR TITLE
added KDE color schemes & make gtk theme work properly

### PR DESCRIPTION
**Pull request by hydroakri**

### CODE REVIEW

**Comment by kepano** [comment]
Thanks! What is the purpose of the assets? Are those necessary?

**Comment by hydroakri** [comment]
The assets is from [adw-gtk3](https://github.com/lassekongo83/adw-gtk3)
remove assets can cause the missing of slider and some buttons

**Comment by kepano** [comment]
From what I can see, those assets don't seem to be using the Flexoki colors, is that intentional?

**Comment by hydroakri** [comment]
It has been repainted.
But I have a small problem: gtk needs a full range of color tones, but the current ones are only light and dark.

**Comment by hydroakri** [comment]
It's done

**Comment by kepano** [comment]
Thanks!

**Pull request merged**
